spring.application.name=vehiclecare-micro

# ===============================
# DATASOURCE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/vehiclecare
spring.datasource.username=vehiclecare_user
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CATALOG SYNC
# ===============================
catalog.sync.enabled=false

# ===============================
# MINIO STORAGE
# ===============================
minio.endpoint=http://localhost:9000
minio.access-key=adminvehiclecare
minio.secret-key=12345678
minio.bucket=vehiclecare
minio.initialize-bucket=true

# ===============================
# MULTIPART
# ===============================
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
